// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP4aAF3aewFiau0bfJk8SWXBrwEPW9HVg',
    appId: '1:469762612706:web:0bea03022975c86ec26dbb',
    messagingSenderId: '469762612706',
    projectId: 'aqua-clean-c5717',
    authDomain: 'aqua-clean-c5717.firebaseapp.com',
    storageBucket: 'aqua-clean-c5717.appspot.com',
    measurementId: 'G-RN0L0340GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpbz4I6MT10rIGeL9rI1ocBMZRYB622bg',
    appId: '1:469762612706:android:af6428e8271a2051c26dbb',
    messagingSenderId: '469762612706',
    projectId: 'aqua-clean-c5717',
    storageBucket: 'aqua-clean-c5717.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnIlxskR0EiDH1icOwonHqmg8YnwSC_NU',
    appId: '1:469762612706:ios:b6dd4de889ac5e5fc26dbb',
    messagingSenderId: '469762612706',
    projectId: 'aqua-clean-c5717',
    storageBucket: 'aqua-clean-c5717.appspot.com',
    iosBundleId: 'com.example.aquaCleanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnIlxskR0EiDH1icOwonHqmg8YnwSC_NU',
    appId: '1:469762612706:ios:4198c86f47f8884cc26dbb',
    messagingSenderId: '469762612706',
    projectId: 'aqua-clean-c5717',
    storageBucket: 'aqua-clean-c5717.appspot.com',
    iosBundleId: 'com.example.aquaCleanApp.RunnerTests',
  );
}
